Update btrfs-sync

diff --git a/btrfs-sync b/btrfs-sync
--- a/btrfs-sync
+++ b/btrfs-sync
@@ -36,8 +36,8 @@ set -e -o pipefail
 
 # help
 print_usage() {
-  echo "Usage: 
-  $BIN [options] <src> [<src>...] [[user@]host:]<dir>
+  echo "Usage:
+  $BIN [options] [[user@]host:]<src> [<src>...] [[user@]host:]<dir>
 
   -k|--keep NUM     keep only last <NUM> sync'ed snapshots
   -d|--delete       delete snapshots in <dst> that don't exist in <src>
@@ -98,6 +98,19 @@ SRC=( "${@:1:$#-1}" )
 DST="${@: -1}"
 
 # detect remote dst argument
+[[ "$SRC" =~ : ]] && {
+  NET_SRC="$( sed 's|:.*||' <<<"$SRC" )"
+  SRC="$( sed 's|.*:||' <<<"$SRC" )"
+  SSH_SRC=( ssh -p "$PORT" -o ServerAliveInterval=5 -o ConnectTimeout=1 -o BatchMode=yes "$NET_SRC" )
+}
+
+[[ "$SSH_SRC" != "" ]] && SRC_CMD=( ${SSH_SRC[@]} ) || SRC_CMD=( eval )
+${SRC_CMD[@]} test -x "$SRC" &>/dev/null || {
+  [[ "$SSH_SRC" != "" ]] && echo "SSH access error to $NET_SRC. Do you have passwordless login setup, and adequate permissions for $SRC?"
+  [[ "$SSH_SRC" == "" ]] && echo "Access error. Do you have adequate permissions for $SRC?"
+}
+
+# detect remote dst argument
 [[ "$DST" =~ : ]] && {
   NET="$( sed 's|:.*||' <<<"$DST" )"
   DST="$( sed 's|.*:||' <<<"$DST" )"
@@ -105,7 +118,8 @@ DST="${@: -1}"
 }
 [[ "$SSH" != "" ]] && DST_CMD=( ${SSH[@]} ) || DST_CMD=( eval )
 ${DST_CMD[@]} test -x "$DST" &>/dev/null || {
-  echo "SSH access error to $NET. Do you have passwordless login setup, and addecuate permissions for $DST?"
+  [[ "$SSH" != "" ]] && echo "SSH access error to $NET. Do you have passwordless login setup, and adequate permissions for $DST?"
+  [[ "$SSH" == "" ]] && echo "Access error. Do you have adequate permissions for $DST?"
   exit 1
 }
 
@@ -122,25 +136,27 @@ ${DST_CMD[@]} "pgrep -f btrfs\ receive &>/dev/null" && { echo "btrfs-sync alread
 ## src checks
 echov "* Check source"
 while read entry; do SRCS+=( "$entry" ); done < <(
-  for s in "${SRC[@]}"; do
-    src="$(cd "$s" &>/dev/null && pwd)" || { echo "$s not found"; exit 1; } #abspath
-    btrfs subvolume show "$src" &>/dev/null && echo "0|$src" || \
-    for dir in $( ls -drt "$src"/* 2>/dev/null ); do
-      DATE="$( btrfs su sh "$dir"/snapshot 2>/dev/null | grep "Creation time:" | awk '{ print $3, $4 }' )" \
-      || continue   # not a subvolume
-      SECS=$( date -d "$DATE" +"%s" )
-      echo "$SECS|$dir/snapshot"
-    done
-  done | sort -V | sed 's=.*|=='
+  "${SRC_CMD[@]}" "
+    for s in "${SRC[@]}"; do
+      src=\"\$(cd \"\$s\" &>/dev/null && pwd)\" || { echo \"\$s not found\"; exit 1; } #abspath
+      btrfs subvolume show \"\$src\" &>/dev/null && echo \"0|\$src\" || \
+      for dir in \$( ls -drt \"\$src\"/* 2>/dev/null ); do
+        DATE=\"\$( btrfs su sh \"\$dir\"/snapshot 2>/dev/null | grep \"Creation time:\" | awk '{ print \$3, \$4 }' )\" \
+        || continue   # not a subvolume
+        SECS=\$( date -d \"\$DATE\" +\"%s\" )
+        echo \"\$SECS|\$dir\"/snapshot
+      done
+    done | sort -V | sed 's=.*|=='
+  "
 )
 [[ ${#SRCS[@]} -eq 0 ]] && { echo "no BTRFS subvolumes found"; exit 1; }
 
 ## check pbzip2
 [[ "$ZIP" == "pbzip2" ]] && {
-                    type pbzip2 &>/dev/null && \
+    "${SRC_CMD[@]}" type pbzip2 &>/dev/null && \
     "${DST_CMD[@]}" type pbzip2 &>/dev/null || {
       echo "INFO: 'pbzip2' not installed on both ends, fallback to 'xz'"
-      ZIP=xz PIZ=unxz 
+      ZIP=xz PIZ=unxz
   }
 }
 
@@ -161,14 +177,14 @@ get_dst_snapshots() {      # sets DSTS DST_UUIDS
   while read entry; do
     DST_UUIDS+=( "$( sed 's=|.*==' <<<"$entry" )" )
     DSTS+=(      "$( sed 's=.*|==' <<<"$entry" )" )
-  done < <( 
+  done < <(
     "${DST_CMD[@]}" "
       DSTS=( \$( ls -d \"$DST\"/* 2>/dev/null ) )
       for dst in \${DSTS[@]}; do
         UUID=\$( sudo btrfs su sh \"\$dst\" 2>/dev/null | grep 'Received UUID' | awk '{ print \$3 }' )
         [[ \"\$UUID\" == \"-\" ]] || [[ \"\$UUID\" == \"\" ]] && continue
         echo \"\$UUID|\$dst\"
-      done" 
+      done"
   )
 }
 
@@ -180,7 +196,7 @@ choose_seed() {      # sets SEED
     # try to get most recent src snapshot that exists in dst to use as a seed
     local RXID_CALCULATED=0
     declare -A PATH_RXID DATE_RXID SHOWP RXIDP DATEP
-    local LIST="$( btrfs subvolume list -su "$SRC" )"
+    local LIST="$( "${SRC_CMD[@]}" sudo btrfs subvolume list -su "$SRC" )"
     SEED=$(
       for id in "${DST_UUIDS[@]}"; do
         # try to match by UUID
@@ -190,9 +206,9 @@ choose_seed() {      # sets SEED
         # try to match by received UUID, only if necessary
         [[ "$PATH_" == "" ]] && {
           [[ "$RXID_CALCULATED" == "0" ]] && { # create table during the first iteration if needed
-            local PATHS=( $( btrfs su list -u "$SRC" | awk '{ print $11 }' ) )
+            local PATHS=( $( "${SRC_CMD[@]}" sudo btrfs su list -u "$SRC" | awk '{ print $11 }' ) )
             for p in "${PATHS[@]}"; do
-              SHOWP="$( btrfs su sh "$( dirname "$SRC" )/$( basename "$p" )" 2>/dev/null )"
+              SHOWP="$( "${SRC_CMD[@]}" sudo btrfs su sh "$( dirname "$SRC" )/$( basename "$p" )" 2>/dev/null )"
               RXIDP="$( grep 'Received UUID' <<<"$SHOWP" | awk '{ print $3     }' )"
               DATEP="$( grep 'Creation time' <<<"$SHOWP" | awk '{ print $3, $4 }' )"
               [[ "$RXIDP" == "" ]] && continue
@@ -215,7 +231,7 @@ choose_seed() {      # sets SEED
 }
 
 exists_at_dst() {
-  local SHOW="$( btrfs subvolume show "$SRC" )"
+  local SHOW="$( "${SRC_CMD[@]}" sudo btrfs subvolume show "$SRC" )"
 
   local SRC_UUID="$( grep 'UUID:' <<<"$SHOW" | head -1 | awk '{ print $2 }' )"
   grep -q "$SRC_UUID" <<<"${DST_UUIDS[@]}" && return 0;
@@ -230,7 +246,7 @@ exists_at_dst() {
 ## sync incrementally
 sync_snapshot() {
   local SRC="$1"
-  [[ -d "$SRC" ]] || return
+  "${SRC_CMD[@]}" test -d "$SRC" || return
 
   exists_at_dst "$SRC" && { echov "* Skip existing '$SRC'"; return 0; }
 
@@ -239,7 +255,7 @@ sync_snapshot() {
   # incremental sync argument
   [[ "$SEED" != "" ]] && {
     local SEED_PATH="$( dirname "$SRC" )/$( basename $SEED )"
-    [[ -d "$SEED_PATH" ]] && 
+    "${SRC_CMD[@]}" test -d "$SEED_PATH" &&
       local SEED_ARG=( -p "$SEED_PATH" ) || \
       echo "INFO: couldn't find $SEED_PATH. Non-incremental mode"
   }
@@ -249,11 +265,15 @@ sync_snapshot() {
   [[ "$SEED_ARG" != "" ]] && echov -n " using seed '$SEED'"
   echo "..."
 
-  btrfs send -q ${SEED_ARG[@]} "$SRC" \
+  "${SRC_CMD[@]}" \
+  sudo btrfs send -q ${SEED_ARG[@]} "$SRC" \
     | "$ZIP" \
     | "${PV[@]}" \
     | "${DST_CMD[@]}" "${PIZ[@]} | sudo btrfs receive \"$DST\" 2>&1 |(grep -v -e'^At subvol ' -e'^At snapshot '||true)" \
-    || exit 1;
+    || {
+      "${DST_CMD[@]}" sudo btrfs subvolume delete "$DST"/"$( basename "$SRC" )" 2>/dev/null
+      return 1;
+    }
 
   # update DST list
   DSTS+=("$DST/$( basename "$SRC" )")
@@ -267,7 +287,13 @@ sync_snapshot() {
 echov "* Check destination"
 get_dst_snapshots "$DST" # sets DSTS DST_UUIDS
 for src in "${SRCS[@]}"; do
-  sync_snapshot "$src"
+  sync_snapshot "$src" && RET=0 || RET=1
+  for i in $(seq 1 2); do
+    [[ "$RET" != "1" ]] && break
+    echo "* Retrying '$src'..."
+    sync_snapshot "$src" && RET=0 || RET=1
+  done
+  [[ "$RET" == "1" ]] && { echo "Abort"; exit 1; }
 done
 
 #----------------------------------------------------------------------------------------------------------
